"""create audit_logs table with model_id as string

Revision ID: 63ddd3d48607
Revises: 20250429_update_period_table
Create Date: 2025-05-07 17:01:18.849144

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "63ddd3d48607"
down_revision = "20250429_update_period_table"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.alter_column('XaStatus',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.alter_column('XaStatus',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Deactive'::character varying"),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
